### ISSUE TITLE
1.20.1?

### ISSUE THREAD

**Issue by tmuaprep** [AmibeSkyfy16/ShulkerBoxRecursion#1]

**Comment by AmibeSkyfy16** [comment]
You're in luck, it's been months since I've coded and here, today, as luck would have it, I download intellij and connect to github, plus it's an easy-to-update mod. So it'll be done before you know it.

**Comment by tmuaprep** [comment]
That's insane haha, glad to hear it :)

**Comment by AmibeSkyfy16** [comment]
Its done on modrinth:
https://modrinth.com/mod/shulkerboxrecursion/versions#all-versions

The project is not accepted by CurseForge and yeah its normal, CF SUCKS A LOT ! XD
